spring:
  profiles:
    active: local
  application:
    name: '@project.name@'
  messages:
    basename: messages/messages
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/company
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    username: admin
    password: 123456
    hikari:
      pool-name: mpe-ph-db-pool
      maximum-pool-size: 30
      max-lifetime: 4000
      connection-timeout: 5000
      minimum-idle: 250
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        socketTimeout: 30
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: drop-and-create
      hibernate.jdbc.batch_size: 100

server:
  port: 9792
  error:
    whitelabel:
      enabled: false
