spring:
  profiles:
    active: local
  application:
    name: 'couchbase-sdk-demo'

couchbase:
  connection-string: couchbase://127.0.0.1
  user-name: admin
  password: 123456
  bucket-company:
    name: Company
    user-name: Company
    password: com123
  bucket-employee:
    name: Employee
    user-name: Employee
    password: emp123

server:
  port: 9292
