version: '3.7'
services:
  couchbase:
    build:
      context: couchbase/.
    healthcheck:
      test: "curl --fail http://localhost:8091/pools"
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - 8091-8094:8091-8094
      - 11210:11210


# docker run -d --name couchbase-sdk-demo -p 8091-8094:8091-8094 -p 11210:11210 couchbase
# admin 123456