version: '3.7'
services:
  postgresql:
    image: postgres:9.6.16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=company
    ports:
      - 5432:5432
  couchbase:
    build:
      context: couchbase/.
    healthcheck:
      test: "curl --fail http://localhost:8091/pools"
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - 8091-8094:8091-8094
      - 11210:11210