spring:
  profiles:
    active: local
  application:
    name: '@project.name@'

couchbase:
  connection-string: localhost
  user-name: admin
  password: 123456
  bucket-company:
    name: Company
    user-name: Company
    password: com123

server:
  port: 9292
