version: '3.7'
services:
  postgresql:
    image: postgres:9.6.16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mediumdb
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  couchbase:
    image: couchbase:6.6.1
    healthcheck:
      test: "curl --fail http://localhost:8091/pools"
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./couchbase/init.sh:/opt/couchbase/init.sh
      - ./_export:/import
    entrypoint: /opt/couchbase/init.sh
    ports:
      - 8091-8094:8091-8094
      - 11210:11210